from setuptools import setup

setup(name = "bnctools",
      license = 'GNU Public License 3.0',
      version = "0.0.0",
      description = "Tools for processing British National Corpus",
      author = "Mark Andrews",
      author_email = "mjandrews.net@gmail.com",
      packages=["bnctools"],
      scripts = [
        'scripts/getbnc2554.sh',
        'scripts/getbncparagraphs.sh',
        'scripts/getvocabularylists.sh'
      ],
      install_requires=[
        'backports-abc>=0.5',
        'backports.shutil-get-terminal-size>=1.0.0',
        'beautifulsoup4>=4.5.1',
        'bs4>=0.0.1',
        'certifi>=2016.9.26',
        'configobj>=5.0.6',
        'configparser>=3.5.0',
        'decorator>=4.0.10',
        'docopt>=0.6.2',
        'entrypoints>=0.2.2',
        'enum34>=1.1.6',
        'functools32>=3.2.3.post2',
        'futures>=3.0.5',
        'ipykernel>=4.5.1',
        'ipyparallel>=5.2.0',
        'ipython>=5.1.0',
        'ipython-genutils>=0.1.0',
        'ipywidgets>=5.2.2',
        'Jinja2>=2.8',
        'jsonschema>=2.5.1',
        'jupyter>=1.0.0',
        'jupyter-client>=4.4.0',
        'jupyter-console>=5.0.0',
        'jupyter-core>=4.2.0',
        'lxml>=3.6.4',
        'MarkupSafe>=0.23',
        'mistune>=0.7.3',
        'mpi4py>=2.0.0',
        'mpmath>=0.19',
        'nbconvert>=4.2.0',
        'nbformat>=4.1.0',
        'notebook>=4.2.3',
        'numpy>=1.11.2',
        'pathlib2>=2.1.0',
        'pexpect>=4.2.1',
        'pickleshare>=0.7.4',
        'prompt-toolkit>=1.0.9',
        'ptyprocess>=0.5.1',
        'Pygments>=2.1.3',
        'pyzmq>=16.0.2',
        'qtconsole>=4.2.1',
        'simplegeneric>=0.8.1',
        'singledispatch>=3.4.0.3',
        'six>=1.10.0',
        'sympy>=1.0',
        'terminado>=0.6',
        'tornado>=4.4.2',
        'traitlets>=4.3.1',
        'wcwidth>=0.1.7',
        'widgetsnbextension>=1.2.6'
        ]
      )
